GUI almost done

diff --git a/ltfsa_gui/www/cgi-bin/ltfsa_gui_config b/ltfsa_gui/www/cgi-bin/ltfsa_gui_config
--- a/ltfsa_gui/www/cgi-bin/ltfsa_gui_config
+++ b/ltfsa_gui/www/cgi-bin/ltfsa_gui_config
@@ -1,6 +1,6 @@
 #!/bin/tcsh -f
 #
-#  ltfsa_cli
+#  ltfsa_gui
 #  Version: 0.0.1
 #  Authors: L. Boch
 #
@@ -14,7 +14,7 @@
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU Affero General Public License for more details.
+# GNU General Public License for more details.
 #
 # You should have received a copy of the GNU Affero General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
@@ -30,6 +30,9 @@ if ( !($?pdir) ) then
 endif
 set curloptions = `cat $pdir/config/curloptions`
 set ltfsaserverurl = `cat $pdir/config/ltfsaserverurl`
+set ltfsaserverurlsav = "$ltfsaserverurl"
+#removing /cgi-bin
+set ltfsaserverurl = `dirname $ltfsaserverurl`
 echo "content-type: text/html\n"
 if ( $REQUEST_METHOD != "GET" ) then
 	echo "400"
@@ -39,52 +42,33 @@ if ( $REQUEST_METHOD != "GET" ) then
 endif
 set inquery = `echo $QUERY_STRING | cut -d'&' -f1- --output-delimiter=' ' | cut -d'=' -f1- --output-delimiter=' '`
 set inquery = `$pdir/bin/clean.querystring $inquery`
-set service = null
-set ltfsaquery = ""
 set i = 1
 while ( $i < $#inquery )
-        if ( "$inquery[$i]" == "service" ) then
+        if ( "$inquery[$i]" == "ltfsaserverurl" ) then
                 @ i++
-                set service = "$inquery[$i]"
+                set ltfsaserverurl = "$inquery[$i]"
+		curl $curloptions "$ltfsaserverurl" -o $pdir/logs/$this.$$.out >& $pdir/logs/$this.$$.log
+		set ret = $?
+		if ( $ret ) then
+			echo "403"
+			echo "Bad request"
+			echo "$this failed on ltfsa service $ltfsaserverurl"
+			exit 2
+		endif
 	else
-                set var = "$inquery[$i]"
-                @ i++
-                set value = "$inquery[$i]"
-		if ( "$value != "null" && ( "$var" == "TaskID" || "$var" == "TapeID" ||| "$var" == "PoolName" ||| "$var" == "FileName" || "$var" == "Checksum" || "$var" == "ChecksumFile" || "$var" == "DestPath" || "$var" == "Date" || "$var" == "FromDate" || "$var" == "ToDate" || "$var" == "Status" || "$var" == "LTFSAction" || "$var" == "Format" ) ) then
-		set ltfsaquery = "$ltfsaquery&$var=$value"
-        else
 		echo "400"
 		echo "Bad request "
-		echo "$this unknown $var"
-                exit 1
-        endif
+		echo "$this unknown $var=$value"
+       	        exit 1
+	endif
         @ i++
 end
-#
-#Sanity Check
-#
-#
-#Calling the service
-#
-curl $curloptions "$ltfsaserverurl/$service?Output=XML${ltfsaquery}" -o $pdir/logs/$this.$$.out >& $pdir/logs/$this.$$.log
-set ret = $?
-	echo "500"
-	echo "Server Error"
-	echo "$this failed on ltfsa service $service with $ltfsaquery."
-	exit 2
+#Modifying config
+if ( "$ltfsaserverurl/cgi-bin" != "$ltfsaserverurlsav" ) then
+	cp $pdir/config/ltfsaserverurl $pdir/config/ltfsaserverurl.bak
+	echo "$ltfsaserverurl/cgi-bin" > $pdir/config/ltfsaserverurl
 endif
-#
-#Filtering XML Output through our best XSL
-#
-xsltproc $pdir/xsl/ltfsa_gui.xsl $pdir/logs/$this.$$.out > $pdir/logs/$this.$$.html
-set ret = $?
-	echo "500"
-	echo "Server Error"
-	echo "$this failed on processing the output ofltfsa service $service with $ltfsaquery."
-	exit 3
-endif
-cat $pdir/logs/$this.$$.html
-#
-#End of the story
-#
+#Giving form for changing again
+set ltfsaserverurlsed = `echo $ltfsaserverurl | sed -e s/'\/'/'\\\/'/g`
+cat $pdir/share/ltfsa_gui_config.html | sed -e s/'+++LTFSASERVERURL+++'/$ltfsaserverurlsed/g 
 exit 0
